import '../../features/contacts/domain/contact.dart';

final nationalEmergencyContacts = <Contact>[
  Contact.seed(
    id: 'quick-police-100',
    category: 'Emergency Services',
    subcategory: 'Police',
    organisationName: 'Police',
    hotlineCode: '100',
    isEmergency: true,
    is247: true,
    verificationStatus: 'Verified',
    sourceType: 'Police / Security Official',
  ),
  Contact.seed(
    id: 'quick-fire-101',
    category: 'Emergency Services',
    subcategory: 'Fire',
    organisationName: 'Fire',
    hotlineCode: '101',
    isEmergency: true,
    is247: true,
    verificationStatus: 'Verified',
  ),
  Contact.seed(
    id: 'quick-ambulance-102',
    category: 'Health & Ambulance',
    subcategory: 'Ambulance',
    organisationName: 'Ambulance',
    hotlineCode: '102',
    isEmergency: true,
    is247: true,
    verificationStatus: 'Verified',
  ),
  Contact.seed(
    id: 'quick-traffic-103',
    category: 'Police & Security',
    subcategory: 'Traffic',
    organisationName: 'Traffic Police',
    hotlineCode: '103',
    isEmergency: true,
    verificationStatus: 'Verified',
    sourceType: 'Police / Security Official',
  ),
  Contact.seed(
    id: 'quick-child-1098',
    category: 'Women & Children',
    subcategory: 'Child Helpline',
    organisationName: 'Child Helpline',
    hotlineCode: '1098',
    isEmergency: true,
    verificationStatus: 'Needs Review',
  ),
  Contact.seed(
    id: 'quick-women-1145',
    category: 'Women & Children',
    subcategory: 'Women Helpline',
    organisationName: 'Women Helpline',
    hotlineCode: '1145',
    isEmergency: true,
    is247: true,
    verificationStatus: 'Verified',
    sourceType: 'Official Government',
  ),
  Contact.seed(
    id: 'quick-tourist-1144',
    category: 'Travel & Tourism',
    subcategory: 'Tourist Police',
    organisationName: 'Tourist Police',
    hotlineCode: '1144',
    isEmergency: true,
    verificationStatus: 'Needs Review',
    sourceType: 'Police / Security Official',
  ),
  Contact.seed(
    id: 'quick-disaster-1149',
    category: 'Disaster & Rescue',
    subcategory: 'Disaster / NEOC',
    organisationName: 'Disaster / NEOC',
    hotlineCode: '1149',
    isEmergency: true,
    verificationStatus: 'Needs Review',
    sourceType: 'Official Government',
  ),
  Contact.seed(
    id: 'quick-nea-1150',
    category: 'Electricity & Utilities',
    subcategory: 'Electricity',
    organisationName: 'NEA / Electricity',
    hotlineCode: '1150 / 1151',
    isEmergency: true,
    verificationStatus: 'Needs Review',
    sourceType: 'Utility Official',
  ),
  Contact.seed(
    id: 'quick-hello-sarkar-1111',
    category: 'Government Complaints',
    subcategory: 'Hello Sarkar',
    organisationName: 'Hello Sarkar',
    hotlineCode: '1111',
    verificationStatus: 'Needs Review',
    sourceType: 'Official Government',
  ),
  Contact.seed(
    id: 'quick-home-ministry-1112',
    category: 'Government Services',
    subcategory: 'Home Ministry',
    organisationName: 'Home Ministry',
    hotlineCode: '1112',
    verificationStatus: 'Needs Review',
    sourceType: 'Official Government',
  ),
];
